CREATE EVENT SESSION [rest] ON SERVER
	ADD EVENT sqlserver.external_rest_endpoint_summary,
	ADD EVENT sqlserver.ai_generate_embeddings_summary
WITH
(
	MAX_MEMORY = 4096 KB,
	EVENT_RETENTION_MODE = ALLOW_SINGLE_EVENT_LOSS,
	MAX_DISPATCH_LATENCY = 30 SECONDS,
	MAX_EVENT_SIZE = 0 KB,
	MEMORY_PARTITION_MODE = NONE,
	TRACK_CAUSALITY = OFF,
	STARTUP_STATE = OFF
);
GO